### PR TITLE
Add version to score info; close #2

### LINKED ISSUE #2: tracking scores
I figured that the scores currently don't say much, as long as we don't save the version of the game with them... So we know how "hard" it was to get the points.
That's something that I am happily willing to let you, @LFalch, do that.

Meanwhile, I'll use some of my time to code up the leaderboard

### PR DESCRIPTION
**Pull request by LFalch**
It still needs to be set up on the SQL server.

### CODE REVIEW

**Comment by mtib** [comment]
Looks great. I'll set up the Server. :+1: 

EDIT: Done

**Comment by mtib** [comment]
I am a bit scared of having dot's in the GET-url.

**Comment by LFalch** [comment]
As far as I could research, there shouldn't be much danger with those dots, but I share your concern.

**Comment by mtib** [comment]
> It feels like we should actively escape the dot (and other stuff, even tho' we are prepared on the backend). [escape](http://www.the-art-of-web.com/javascript/escape/)() doesn't escape it, but it could be %2E for url encoding, if you ask me.

After thinking about it, it seems like it is unnecessary to do any more escaping to it, the back end will handle it!

**Comment by LFalch** [comment]
Great!

**Pull request merged**
